config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'pages#home'
    get '/about', to: 'pages#about'
    get '/support', to: 'pages#support'
    resources :protests, only: %i[index show new create] do
      resources :protest_assaults, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assault_category.rb
class AssaultCategory < ApplicationRecord
  has_many :protest_assaults
  has_many :protests, through: :protest_assaults
  validates :name, presence: true, uniqueness: true
end

app/models/protest.rb
class Protest < ApplicationRecord
  belongs_to :station
  has_many :protest_assaults, dependent: :destroy
  has_many :assault_categories, through: :protest_assaults

  validates :experienced, inclusion: { in: [true, false] }
  validates :date, presence: true
  validates :description, presence: true
  validates :station, presence: true
end

app/models/protest_assault.rb
class ProtestAssault < ApplicationRecord
  belongs_to :protest
  belongs_to :assault_category

  validates_uniqueness_of :protest, :scope => [:assault_category]
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @protests = Protest.all
    @count_protests = Protest.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count
    @count_locations = Protest.group(:station).where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count.count
    @count_shares = rand(6..14)
  end

  def about
  end
end

app/controllers/protest_assaults_controller.rb
class ProtestAssaultsController < ApplicationController
  def create
    @protest = Protest.find(params[:protest_id])
    @assault_categories = AssaultCategory.where(id: params[:protest_assault][:assault_category])
    @assault_categories.each do |assault_category|
      protest_assault = ProtestAssault.new
      protest_assault.protest = @protest
      protest_assault.assault_category = assault_category
      protest_assault.save
    end
    redirect_to protest_path(@protest)
  end
end

app/controllers/protests_controller.rb
class ProtestsController < ApplicationController
  def index
    if params[:search_category] || params[:search_station] || params[:start_date]
      @protests = query_protests(params[:search_category], params[:search_station], params[:start_date])
    else
      @protests = Protest.all.order(date: :desc)
    end

    @stations = Station.all

    @markers = @stations.map do |station|
      {
        lat: station.latitude,
        lng: station.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { station: station }),
        number_of_protests: Protest.where(station_id: station).count
      }
    end
  end

  def show
    @protest = Protest.find(params[:id])
  end

  def new
    @protest = Protest.new
    @stations = Station.all
  end

  def create
    @protest = Protest.new(strong_params)
    if @protest.other_category == ""
      @protest.other_category = nil
    end

    if @protest.save
      flash[:notice] = 'Successfully checked in'
      redirect_to protests_path
    else
      render :new
    end
  end

  private

  def query_protests(category_param, station_param, date_param)
    protests = []

    if category_param.present?
      protests = Protest.joins(:protest_assaults).where(protest_assaults: { assault_category_id: category_param })
    end

    if !station_param.empty?
      if not protests.empty?
        protests = protests.where(station_id: station_param)
      else
        protests = Protest.where(station_id: station_param)
      end
    end

    if date_param
      if !date_param.empty?
        date = Date.parse(date_param)
        if !protests.empty?
          protests = protests.where(date: date)
        else
          protests = Protest.where(date: date)
        end
      end
    end

    return protests
  end

  def build_geojson
    {
      type: "FeatureCollection",
      features: @protests.map(&:to_feature)
    }
  end

  def strong_params
    params.require(:protest).permit(:experienced, :date, :time, :description, :station_id, :other_category, assault_category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google Tag Manager -->
    <script>
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-M4MN7Z7');
    </script>
    <!-- End Google Tag Manager -->
    <title>imvisible: Protest against sexual harassment on public transport</title>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <meta property="og:url" content="http://www.im-visible.com/protests" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="imvisible: protesting sexual harassment on public transport" />
    <meta property="og:description" content="Sexual harassment happens every day and it goes unnoticed." />
    <meta property="og:image" content="https://images.unsplash.com/photo-1482678264299-6eb83b49cb42?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1200&h=630&q=80" />
    <%= favicon_link_tag %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <link rel="manifest" href="/manifest.json">
    <%= render 'shared/ios_pwa_links' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-179474889-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-179474889-1');
    </script>
    <!-- Hotjar Tracking Code for www.im-visible.com -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:2256862,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
      <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M4MN7Z7"
      height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <%= render 'shared/navbar' %>
    <%= yield %>
    <% if flash[:notice] %>
      <div class="flash flash-success alert alert-dismissible fade show" role="alert">
        <div class="flash-close">
          <a data-dismiss="alert" aria-label="Close">
            <i class="fas fa-times big-icon"></i>
          </a>
        </div>
        <div class="flash-text pb-3">
          <span><%= t ".alert_html" %></span>
        </div>
      </div>
    <% end %>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v8.0" nonce="ndqirQjf"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container-fluid page-about bg-white m-0 p-0">
  <div class="mission-space">
    <h1 class="about-header text-center"><%= t ".about_header" %></h1>
    <h1 class="about-name text-center">i<strong>m</strong>visible</h1>
  <div class="circles-about mt-4">
    <div id="about-mission-circle">
      <p class="mission-text text-center"><strong><%= t ".mission_title" %></strong><br><%= t ".mission_text_html" %></p>
    </div>
      <!-- <div id="about-share-circle">
        <p class="about-share text-center"><%= t ".follow_imvisible_html" %></p>
        <div class="social-media-links text-center">
          <a href="https://twitter.com/imvisible_mx" class="fab fa-twitter" target="_blank"></a>
          <a href="https://www.instagram.com/_imvisible/" class="fab fa-instagram" target="_blank"></a>
        </div>
      </div> -->
    <div id="about-vision-circle">
      <p class="vision-text text-center"><strong><%= t ".vision_title" %></strong><br><%= t ".vision_text_html" %></p>
    </div>
  </div>
  </div>
  <div class="other-support-section text-center m-0 pl-3 pr-3 pt-3 pb-5" id="support-section">
    <!-- <div class="border-circle-about1"></div> -->
    <h1 class="support-header text-center pt-5 pb-3"><%= t ".interest_sites_title" %></h1>
    <div class="row">
      <div class="support-item">
        <img src="https://images.unsplash.com/photo-1547937084-4d587301a545?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&h=1500&q=80" class="avatar-large">
        <div class="support-text-left">
          <p><strong><%= t ".womens_rights" %></strong></p>
          <a href="https://mexico.unwomen.org/"><p><em><%= t ".un_women" %></em></p></a>
          <a href="https://www.semujeres.cdmx.gob.mx/"><em><p><%= t ".secretary_women" %></p></em></a>
          <a href="https://www.heforshe.org/es"><em><p>HeForShe</p></em></a>
        </div>
      </div>
       <div class="support-item">
        <img src="https://images.unsplash.com/photo-1539541417736-3d44c90da315?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&h=1500&q=80" class="avatar-large">
        <div class="support-text-left">
          <p><strong><%= t ".support_title" %></strong></p>
          <a href="https://www.metro.cdmx.gob.mx/tramites-y-servicios/servicios/que-hacer-en-caso-de-acoso-sexual"><p><em><%= t ".what_to_do" %></em></p></a>
          <a href="https://www.fgjcdmx.gob.mx/nuestros-servicios/en-linea/mp-virtual/centros-de-justicia-para-las-mujeres"><p><em><%= t ".justice_centers" %></em></p></a>
        </div>
      </div>
      <div class="support-item">
        <img src="https://images.unsplash.com/photo-1551406483-3731d1997540?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&h=668&q=80" class="avatar-large">
        <div class="support-text-left">
          <p><strong><%= t ".read_more" %></strong></p>
          <a href="https://www.reuters.com/article/us-transport-women-poll-mexico/exclusive-mexico-citys-transport-ranked-as-most-dangerous-for-women-global-poll-idUSKCN1NK059"><p><em><%= t ".most_dangerous" %></em></p></a>
          <a href="https://www.londonreconnections.com/2019/mind-the-gender-gap-the-hidden-data-gap-in-transport/"><p><em><%= t ".gender_gap" %></em></p></a>
        </div>
      </div>
    </div>
   <!--  <div class="border-circle-about2"></div> -->
  </div>
  <div class="faq-section" id="section-faq">
    <h1 class="support-header text-center pt-5 pb-3"><%= t ".faq" %></h1>
    <div class="faq-item">
      <h1 class="faq-question" data-toggle="collapse" href="#collapseExample1" role="button" aria-expanded="false" aria-controls="collapseExample"><%= t ".what_will_happen_question" %></h1>
      <p class="collapse show faq-answer" id="collapseExample1"><%= t ".what_will_happen_answer" %></p>
    </div>
    <div class="faq-item">
      <h1 class="faq-question" data-toggle="collapse" href="#collapseExample2" role="button" aria-expanded="false" aria-controls="collapseExample"><%= t ".involved_question" %></h1>
      <p class="collapse show faq-answer" id="collapseExample2"><%= t ".involved_answer_html" %></p>
    </div>
    <div class="faq-item">
      <h1 class="faq-question" data-toggle="collapse" href="#collapseExample3" role="button" aria-expanded="false" aria-controls="collapseExample"><%= t ".psychological_help_question_html" %></h1>
      <p class="collapse show faq-answer" id="collapseExample3"><%= t ".psychological_help_answer_html" %></p>
    </div>
    <div class="faq-item">
      <h1 class="faq-question" data-toggle="collapse" href="#collapseExample4" role="button" aria-expanded="false" aria-controls="collapseExample"><%= t ".other_cities_question_html" %></h1>
      <p class="collapse show faq-answer" id="collapseExample4"><%= t ".other_cities_answer_html" %></p>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<div class="container-fluid home-page bg-white m-0 p-0">
  <div class="row intro-section text-center m-0 p-4">
    <h1 class="header animate__animated animate__fadeIn text-center">i<strong>m</strong>visible</h1>
    <h2 class="subheader animate__animated animate__fadeIn text-center"><%= t ".slogan_html" %></h2>
    <div class="button-div"><a href="protests/new"><button type="button" class="protest-button"><%= t '.protest' %></button></a></div>
  </div>
  <div class="options-section text-center m-0 p-3">
    <!-- <div class="border-circle-home1"></div> -->
    <div class="row">
      <a href="/protests/new" class="link-item">
        <img src="https://images.unsplash.com/photo-1560537083-b510af644919?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&h=1500&q=80" class="avatar-large">
        <p class="link-item-title"><strong><%= t ".share_an_incident_title" %></strong></p>
        <p><%= t ".share_an_incident_text" %></p>
      </a>
      <a href="/protests" class="link-item">
        <img src="https://images.unsplash.com/photo-1584291527935-456e8e2dd734?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1250&h01250&q=80" class="avatar-large">
        <p class="link-item-title"><strong><%= t ".have_a_look_title" %></strong></p>
        <p><%= t ".have_a_look_text" %></p>
      </a>
    </div>
    <div class="row">
      <a href="/about/#support-section" class="link-item">
        <img src="https://images.unsplash.com/photo-1527525443983-6e60c75fff46?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=664&h=664&q=80" class="avatar-large">
        <p class="link-item-title"><strong><%= t ".get_support_title" %></strong></p>
        <p><%= t ".get_support_text" %></p>
      </a>
      <a href="/about/#section-faq" class="link-item">
        <img src="https://images.unsplash.com/photo-1484069560501-87d72b0c3669?ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&h=1500&q=80" class="avatar-large">
        <p class="link-item-title"><strong><%= t ".faq_title" %></strong></p>
        <p><%= t ".faq_text_html" %></p>
      </a>
    </div>
    <!-- <div class="border-circle-home2"></div> -->
  </div>
  <div class="row today-section text-center bg-white m-0 p4">
    <h1 class="today-header pt-5"><%= t ".city" %></h1>
    <p class="today-date"><%= l(Date.today, format: :long) %></p>
    <div class="circles">
      <div id="today-big-circle"></div>
      <div id="protest-circle">
        <p class="data-number"><%= @count_protests %></p>
        <p class="data-label"><%= t '.protests', count: @count_protests %></p>
      </div>
      <div id="location-cirlce">
        <p class="data-number"><%= @count_locations %></p>
        <p class="data-label"><%= t ".locations", count: @count_locations %></p>
      </div>
      <div id="outer-share-circle"></div>
      <div id="share-circle">
        <p class="data-number"><%= @count_shares %></p>
        <p class="data-label"><%= t ".shares", count: @count_shares %></p>
      </div>
    </div>
    <div class="share-info mb-4">
      <h5><%= t ".share_html" %></h5>
      <div class="share-buttons">
      <div class="fb-share-button" data-href="http://www.im-visible.com/protests/" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.im-visible.com%2Fprotests%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore"><%= t ".facebook" %></a></div>
        <a href="https://twitter.com/intent/tweet?button_hashtag=imvisible&ref_src=twsrc%5Etfw" class="twitter-hashtag-button" data-text="Sexual harassment happens every day and it goes unnoticed -- " data-url="http://www.im-visible.com/protests" data-show-count="false"><%= t ".tweet" %></a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/pages/support.html.erb
<div class="container-fluid support">
 <div class="support-page">
    <h1 class="support-header text-center">SUPPORT</h1>
    <h1 class="support-name text-center">i<strong>m</strong>visible</h1>
  </div>
  <div class="mt-4 col-11 col-md-6 col-lg-6 col-xl-4 container-fluid">
    <p class="text-justify"><%= t ".text_1_html" %></p>
    <p class="text-justify"><%= t ".text_2_html" %></p>
  </div>
  <div class="support-links mt-5 mb-5 col-sm-8 col-md-6 container-fluid text-center">
    <a href="https://www.buymeacoffee.com/imvisible" target="_blank"><button class="support-large-btn pt-2 pb-2"><%= t ".donate-button" %></button></a>
    <br><br>
    <a href="mailto:info@im-visible.com?subject=Quiero ser una embajadora"><button class="support-btn pt-2 pb-2"><%= t ".ambassador" %></button></a>
    <br>
    <a href="https://twitter.com/imvisible_mx" target="_blank"><button class="mt-3 support-btn pt-2 pb-2"><%= t ".twitter" %></button></a>
    <br>
    <a href="https://www.instagram.com/_imvisible/" target="_blank"><button class="mt-3 support-btn pt-2 pb-2"><%= t ".instagram" %></button></a>
  </div>
</div>
<div class="p-3"></div>
<%= render 'shared/footer' %>

app/views/protests/_filter-form.html.erb
<%= form_tag protests_path, method: :get do %>
  <%= select_tag :search_station, options_for_select(Station.all.map { |station| [station.name, station.id] }.unshift([t(".select-station"), ""]), selected: params[:search_station]), class: "search_station" %>
  <br>
  <%= select_tag :search_category, options_for_select(AssaultCategory.all.map { |station| [station.name, station.id] }.unshift([t(".select-category"), ""]), selected: params[:search_category]), class: "search_category" %>
  <br>
  <%= date_field_tag :start_date, params[:start_date], class: "search_date" %>
  <br>
  <%= submit_tag t(".search"), class: "btn see-results animate__animated animate__pulse animate__slower animate__infinite" %>
  <br>
  <%= link_to t(".clear"), "/protests?", class: "restore-link" %>
<% end %>

app/views/protests/_form.html.erb
<%= simple_form_for @protest do |f| %>
    <!-- Witness -->
    <div class="experienced-select flex-50 mr-1">
      <div class="form-check-experienced experienced">
        <input class="form-check-experienced-input radio_buttons optional" type="radio" value="0" name="protest[experienced]" id="protest_experienced_0">
        <label class="form-check-experienced-label collection_radio_button experience-label" for="protest_experienced_0" id='label-0'>
          <%= t ".experienced" %>
        </label>
      </div>
      <div class="form-check-experienced flex-50 witnessed ml-1">
        <input class="form-check-experienced-input radio_buttons optional" type="radio" value="1" name="protest[experienced]" id="protest_experienced_1">
        <label class="form-check-experienced-label collection_radio_buttons experience-label" for="protest_experienced_1" id='label-1'>
          <%= t ".witnessed" %>
        </label>
      </div>
    </div>
    <h3><%= t ".location_label" %></h3>
    <div id="select-station-container">
      <%= f.association :station, as: :select, label_html: { class:"no-label" } %>
    </div>
    <h3 class="mt-3"><%= t ".date_label" %></h3>
    <div class="flex-50">
      <div class="date-select">
        <%= f.input :date, wrapper_html: { class: 'flex-select' }, as: :date, html5: true, label_html: { class:"no-label" } %>
      </div>
      <div class="time-select">
        <%= f.input :time, placeholder: "7:00 - 8:00", label_html: { class:"no-label" } %>
      </div>
    </div>

    <h3><%= t ".assault_type_label" %></h2>
    <div class="row">
        <% AssaultCategory.all.each do |category| %>
        <div class="col-6">
          <label class="label assault-category-name" for="protest_assault_category_ids_<%= category.id %>">
          <span><%= category.name.capitalize %></span>
          <input type="checkbox" class="checkbox" value="<%= category.id %>" name="protest[assault_category_ids][]" id="protest_assault_category_ids_<%= category.id %>"/>
          <span class="check-mark"></span>
          </label>
        </div>
        <% end %>
  </div>

  <div class="other_category-input">
    <div class="other-box">
      <label class="label other-category-name"><span><%= t ".other" %></span>
        <input type="checkbox" class="checkbox" id="other_category_checkbox"/>
        <span class="check-mark"></span>
      </label>
    </div>
    <div class="other-field">
      <%= f.input :other_category, label_html: { class:"no-label" }, input_html: { id: "other_category_field" } %>
    </div>
  </div>

  <div class="description-box">
    <%= f.input :description, placeholder: t(".description_placeholder"), label_html: { class:"no-label" }  %>
  </div>
  <div class="center-button">
    <div class="button-div">
      <%= f.button :submit, t(".protest"), class: 'btn protest-btn' %>
    </div>
  </div>
<% end %>
<p class="disclaimer"><%= t ".disclaimer" %></p>

app/views/protests/_info_window.html.erb
<%= link_to t(".see_all_per_station", station: station.name), protests_path(search_station: station.id), class:"popup-text" %>

app/views/protests/new.html.erb
<div class="all-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-8 col-lg-6 col-xl-6 form-protest">
        <div class="form-protest-body">
          <h1><%= t ".incident" %></h1>
            <%= render "form", protest: @protest %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/protests/show.html.erb
<h1>This is your Protest</h1>
<h3><%= @protest.date %> - <%= @protest.time %></h3>
<p><%= @protest.description %></p>
<p>type of assault:
  <% @protest.protest_assaults.each do |protest_assault| %>
      <%= protest_assault.assault_category.name %>
  <% end %>
</p>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="flex col-8 col-lg-3 align-items-center">
    <i class="far fa-envelope icon-margin"></i>
    <a href="mailto:info@im-visible.com"><p class="no-margin">info@im-visible.com</p></a>
  </div>
  <div class="flex col-3 justify-content-center align-items-center d-none d-md-none d-lg-flex">
    <i class="far fa-copyright icon-margin"></i>
    <p class="no-margin">2020 i<strong>m</strong>visible</p>
  </div>
  <div class="col-4 col-lg-3 flex justify-right align-items-center icons">
    <a href="https://twitter.com/imvisible_mx" class="fab fa-twitter icon-margin" target="_blank"></a>
    <a href="https://www.instagram.com/_imvisible/" class="fab fa-instagram icon-margin" target="_blank"></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- <i class="fas fa-bars absolute little-margin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
<div class="dropdown-menu dropdown-menu-left bg-white" aria-labelledby="navbarDropdown">
  <%= link_to t(".home"), root_path, class: "dropdown-item" %>
  <%= link_to t(".map"), protests_path, class: "dropdown-item" %>
  <%= link_to t(".protest"), new_protest_path, class: "dropdown-item" %>
  <%= link_to t(".about"), about_path, class: "dropdown-item" %>
  <br>
  <% if params[:locale] == 'en' %>
    <%= link_to 'Español', { locale: 'es' }, {class: "green padding-left no-decoration"} %>
  <% else %>
    <%= link_to 'English', { locale: 'en' }, {class: "green padding-left no-decoration"} %>
  <% end %>
  </div>
</div> -->

<div class="navbar">
  <i class="fas fa-bars col-3 padding-none" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
<!--   <div class="col-5">
    <p id="title">i<strong>m</strong>visible</p>
  </div> -->
  <div class="col-3 justify-left padding-none">
    <a href="/support"><button type="button" class="btn donate"><%= t ".donate" %><i class="fas fa-heart ml-1"></i></button></a>
  </div>
  <div class="dropdown-menu dropdown-menu-left bg-white" aria-labelledby="navbarDropdown">
    <%= link_to t(".home"), root_path, class: "dropdown-item" %>
    <%= link_to t(".map"), protests_path, class: "dropdown-item" %>
    <%= link_to t(".protest"), new_protest_path, class: "dropdown-item" %>
    <%= link_to t(".about"), about_path, class: "dropdown-item" %>
    <br>
    <% if params[:locale] == 'en' %>
      <%= link_to 'Español', { locale: 'es' }, {class: "green padding-left no-decoration"} %>
    <% else %>
      <%= link_to 'English', { locale: 'en' }, {class: "green padding-left no-decoration"} %>
    <% end %>
    </div>
  </div>
</div>